[package]
name = "Mandelbrot_Rust"
version = "0.1.1"
authors = ["Mason Gil <masonegil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.2"
num-complex = "0.2.4"
